apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  accessPolicy:
    inbound:
      rules:
        - application: omsorgspenger-oidc-auth-proxy
        - application: k9-los-api
          namespace: default
          cluster: {{clusterFss}}
    outbound:
      rules:
        - application: omsorgspenger-tilgangsstyring
      external:
      {{#each externalHosts as |url|}}
         - host: {{url}}
      {{/each}}
  strategy:
    type: Recreate # Behov fra rapids-and-rivers.
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: {{ database.tier }}
        diskSize: {{ database.diskSize }}
        diskAutoresize: {{ database.diskAutoresize }}
        highAvailability: {{ database.highAvailability }}
        databases:
          - name: omsorgspenger-sak
            envVarPrefix: DATABASE

  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  filesFrom:
    - secret: omsorgspenger-sak-srvusercredentials
      mountPath: /var/run/secrets/nais.io/service_user # Behov fra rapids-and-rivers.
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
    - name: TILGANGSSTYRING_URL
      value: http://omsorgspenger-tilgangsstyring.omsorgspenger.svc.cluster.local
