apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  strategy:
    type: Recreate # Behov fra rapids-and-rivers.
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
      {{#each kafkaBootstrapServers as |server|}}
        - host: {{server}}
      ports:
        - port: 8443
          name: kafka
          protocol: TLS
      {{/each}}

      rules: []
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: omsorgspenger-sak
            envVarPrefix: DATABASE
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  filesFrom:
    - secret: omsorgspenger-sak-srvusercredentials
      mountPath: /var/run/secrets/nais.io/service_user
  envFrom:
    - secret: google-sql-omsorgspenger-sak
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
