apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-sak
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  accessPolicy:
    inbound:
      rules:
        - application: omsorgspenger-oidc-auth-proxy
        - application: k9-los-api
          namespace: default
          cluster: {{clusterFss}}
        - application: omsorgsdager
    outbound:
      rules:
        - application: omsorgspenger-tilgangsstyring
      external:
      {{#each externalHosts as |url|}}
         - host: {{url}}
      {{/each}}
  strategy:
    type: RollingUpdate
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: {{ database.tier }}
        diskSize: {{ database.diskSize }}
        diskAutoresize: {{ database.diskAutoresize }}
        highAvailability: {{ database.highAvailability }}
        databases:
          - name: omsorgspenger-sak
            envVarPrefix: DATABASE

  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
    - name: OMSORGSPENGER_TILGANGSSTYRING_BASE_URL
      value: http://omsorgspenger-tilgangsstyring.omsorgspenger.svc.cluster.local
    - name: KAFKA_RAPID_TOPIC
      value: omsorgspenger.k9-rapid-v2
    - name: KAFKA_CONSUMER_GROUP_ID
      value: omsorgspenger-sak
