CREATE SEQUENCE SEQ_SAKSNUMMER INCREMENT BY 50 MINVALUE 10000000;

CREATE TABLE SAKSNUMMER
(
    IDENTITETSNUMMER VARCHAR(12) NOT NULL,
    SAKSNUMMER VARCHAR(19) NOT NULL,
    PRIMARY KEY (IDENTITETSNUMMER)
);

CREATE INDEX "INDEX_IDENTITETSNUMMER_SAKSNUMMER" ON SAKSNUMMER (IDENTITETSNUMMER);