name: Bygg og deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
  workflow_dispatch:

env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    outputs:
        image: ${{steps.deploy.outputs.image}}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Kjør tester & bygg JAR
        run: ./gradlew test shadowjar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sett image for docker
        run: echo "IMAGE=${BASE_IMAGE}:$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Bygg & last opp Docker image
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          context: .
          tags: ${{env.IMAGE}}

      - name: Sett image for nais deploy
        id: deploy
        run: echo "${IMAGE}" >> $GITHUB_OUTPUT

  slsa-and-vulnerabilities-scan:
    needs: test-and-build
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{needs.test-and-build.deploy.image}}
    steps:

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SALSA_CREDENTIALS }}

      - name: Provenance, upload and sign attestation
        uses: nais/salsa@v0.3
        with:
          key: ${{ secrets.SALSA_KMS_KEY }}
          docker_pwd: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-gcp:
    needs: test-and-build
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{needs.test-and-build.outputs.image}}
    steps:
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/naiserator.yaml
          VARS: nais/dev-gcp.json

      - name: Deploy til prod-gcp
        if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'ci skip')
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/naiserator.yaml
          VARS: nais/prod-gcp.json
